### PR TITLE
setup.sh: fetch latest changes for linux source and yocto-kernel-cache

### PR DESCRIPTION
**Pull request by jkrishnanjanappa**
Hi Jeremy,

Hope You are doing well. Saw dozens of patches in the OE-core
mailing list. All are good ones.

I was using this script as reference for building my project.
I thought of adding below changes would improve the functionality.
May help for your scenario.

'git fetch' does not fetch the latest changes into bare repository
of linux kernel and yocto-kernel-cache under sources-export directory.
git fetch origin $BRANCH:$BRANCH does fetch. The ALLOW_UPDATE
mandates where updates to be fetched or not.

Also when MAKEDROP=1 the project directory will be removed, so
the setup complete should not reference $buildDir name.

Regards,
Jagadeesh

### CODE REVIEW

**Comment by jpuhlman** [comment]
Looks good. Thanks. Things are going well. Hope things are going well on your end.

**Comment by jkrishnanjanappa** [comment]
Thanks for the merge. I am doing good.
There is one more question I wanted to ask, if the LOCAL_SOURCES is set  to
1 then we should set MV_KERNEL_TREE, MV_KERNELCACHE_TREE to the lcoal
sources-export directory (which is what it is doing currently), but if it
is not set or if user sets it 0 then we should set MV_KERNEL_TREE,
MV_KERNELCACHE_TREE  to $TREE.

So the line

echo "$(echo $META)_TREE = '$DL_TREE'" >> conf/local-content.conf

should be

if [ "$LOCAL_SOURCES" = "1" ] ; then
echo "$(echo $META)_TREE = '$DL_TREE'" >> conf/local-content.conf
else
echo "$(echo $META)_TREE = '$TREE'" >> conf/local-content.conf
fi
right?

Regards
Jagadeesh

**Comment by jpuhlman** [comment]
I think it was something that didn't end up getting used. The $(echo $META)_TREE shouldn't be set if local sources is set to 0. The linux-mvista recipe already sets a default value, so it doesn't need to get set at all.

**Comment by jkrishnanjanappa** [comment]
Ok. I thought of that but what if linux-mvista recipe refer to old kernel
source and user wants to check out source given in the REPO_CONFIG variable.

It allows him to edit in config file rather in recipe file which is quite
embedded.

Regards
Jagadeesh

**Pull request merged**
